apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
  labels:
    app: backend
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec: 
      containers: 
       - name: backend
         image: vsacre/backend
         ports:
         - containerPort: 8081
         env:
         - name: MYSQL_IP
           value: mysql
