apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    app: mysql
spec: 
  containers: 
  - name: mysql
    image: mysql:5.7
    ports: 
    - containerPort: 3306
      name: mysql 
    env:
    - name: mysql 
      value: "localhost:3306"
    - name: MYSQL_DATABASE
      value: "independentproject"
    - name: MYSQL_ROOT_PASSWORD
      value: "password"

